version: 0.2
env:
    variables:
        CACHE_CONTROL: 86400
        S3_BUCKET: theavengersleague-frontend
        BUILD_FOLDER: dist/app
        BUILD_ENV: prod
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
            - aws s3 sync dist/index.html s3://theavengersleague-frontend

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
